name = "IX1500ProjectII"
uuid = "56ad7199-57bd-4342-bf20-2e29621e528a"
authors = ["VincentFerrigan <vincent.ferrigan@gmail.com>", "darthzaithe <melocrian@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
